language: python

install:
- openssl aes-256-cbc -K $encrypted_9ab04b43ec0a_key -iv $encrypted_9ab04b43ec0a_iv -in service-account.json.enc -out service-account.json -d
- script/install.sh

script:
- ./script/deploy.sh projects/hello
- ./script/deploy.sh projects/world
- pip -r requirements.txt
- python script/test.py